name: User Service CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

#    services:
#      sonarqube:
#        image: sonarqube:community
#        ports:
#          - 9000:9000
#        options: >-
#          --name sonarqube
#          --health-cmd="curl -f http://localhost:9000 || exit 1"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=10

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK 21 с кешем Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

#      - name: Wait for SonarQube to be ready
#        run: |
#          for i in {1..30}; do
#            if curl -s http://sonarqube:9000 > /dev/null; then
#              echo "SonarQube is up!"
#              break
#            fi
#            echo "Waiting for SonarQube..."
#            sleep 5
#          done

      # 3. Сборка проекта + тесты
#      - name: Build and test
#        run: mvn -B clean verify

      # 4. Анализ кода
#      - name: Analyze with SonarQube
#        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#        with:
#          args:
#            -Dsonar.projectKey=:${{ secrets.SONAR_PROJECT_KEY }}

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=nikita-yatsko_User-Servise \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 5. Установка Docker Buildx
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      # 6. Вход в Docker Hub
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      # 7. Извлекаем метаданные Docker
#      - name: Extract Docker metadata
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#
#      # 8. Сборка и пуш Docker образа
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./docker/Dockerfile
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
