name: User Service CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup JDk
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Build project
      - name: Build project
        run: mvn clean compile

      # Run tests
      - name: Run tests
        run: mvn test

      # Code analysis
      - name: Code analysis with SonarQube
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: ${{ secrets.SONAR_ORG }}
          token: ${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t user-service:latest .

      # Login to Docker Hub (или GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image
      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest
